### ISSUE TITLE
Qb-target

### ISSUE THREAD

**Issue by TheIvan2022** [kartik1410/kartik-loansystem#2]
I am trying to add the support for qb-target but I keep failing with the zone stuff.  is it possible to add it? I am also NEW so idk if I can pos this here or where should I do it?

**Comment by kartik1410** [comment]
qb-target supported added . Kindly refer to latest commit

**Comment by cadburry6969** [comment]
> qb-target supported added . Kindly refer to latest commit

https://github.com/kartik1410/kartik-loansystem/commit/1c8480371b866ba5ca7b06f2289ee1e2675f85f4
